# Generated by Django 3.2 on 2023-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20230404_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expirience',
            field=models.TextField(default='Secret'),
        ),
    ]
